parent=keycloak
import=common/keycloak

stylesCommon=node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css lib/zocial/zocial.css
styles=css/styles.css

kcHtmlClass=
kcBodyClass=weight-tracker-body
kcLoginClass=weight-tracker-login
kcFormCardClass=weight-tracker-card
kcButtonPrimaryClass=btn-wt-primary
kcButtonClass=btn-wt
kcInputClass=wt-input
kcLabelClass=wt-label
