"""add_updated_at_to_measurements

Revision ID: 26e2b6876f8d
Revises: d12c0225fb1b
Create Date: 2026-04-24 22:13:45.608640

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26e2b6876f8d'
down_revision: str | None = 'd12c0225fb1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'updated_at')
    # ### end Alembic commands ###
