"""add_medication_doses

Adds the ``medication_doses`` table: a per-user journal of medication doses
(GLP-1 and similar) annotated onto the weight chart. Hand-written (not
autogenerated) so it can be reviewed against ``db/engine.py``.

Revision ID: c4e5f6a7b8d9
Revises: a3f1c2d4e5f6
Create Date: 2026-07-13 09:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4e5f6a7b8d9'
down_revision: str | None = 'a3f1c2d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'medication_doses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('medication', sa.String(length=100), nullable=False),
        sa.Column('dose_mg', sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column('note', sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(
            'dose_mg IS NULL OR dose_mg > 0',
            name='ck_dose_mg_positive',
        ),
    )
    op.create_index(
        'ix_medication_doses_user_date',
        'medication_doses',
        ['user_id', 'date'],
    )


def downgrade() -> None:
    op.drop_index('ix_medication_doses_user_date', table_name='medication_doses')
    op.drop_table('medication_doses')
